<!DOCTYPE HTML>
<html>
<head>
	<include file="Common@Public/head"/>
	<link href="__PUBLIC__/Admin/css/pop_box.css" rel="stylesheet" />
</head>
<body>
	<block name="body"></block>
	<block name="body2"></block>
    <block name="footer"></block>
	<div id="hidden_box">
		<block name="hidden"></block>
	</div>
	<script type="text/javascript" src="__PUBLIC__/Admin/js/qq1042101197.js"></script>
	<script type="text/javascript">
	var result;
    function iframe_resize(pop_box,self_box){
        pop_box.width(self_box.width()).height(self_box.height());
    }
	$(function($){
        var a=$(window.top.document.getElementById('dialog_frame')),
            b=$('#main_box');
        init_input_img('',function(){
            iframe_resize(a,b);
        });
        iframe_resize(a,b);
		$('#h_submit').click(function(){
			$('#form_1').submit();
		});
	});
	</script>
	<block name="script"></block>
</body>
</html>
